vu:
  data_1cho_starting_cohorts_file_path: "data/00_raw/2022/2023-09-19-15-32-12_ODW204 - VUanalytics EOI Cohorten.zip"
  data_1cho_enrollments_file_path: "data/00_raw/2022/2023-03-21-16-43-54_ODW205 - VUanalytics 1CHO Inschrijving.zip"
  metadata_1cho_decoding_files_dir: "data/00_raw/2022/decoding_files/"
  metadata_institution_name: "VU"
  metadata_institution_BRIN: "21PL"
  fix_duplicated_enrollments: TRUE
  filter_only_own_students: TRUE
  filter_only_gov_funded_programmes: TRUE

synthetic:
  inherits: vu

default:
  inherits: synthetic
